baseURL = 'https://scrabble.lgbt/'
languageCode = 'en-us'
title = 'QISC'
theme = 'risotto'

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
	identifier = "links"
	name = "Links"
	url = "/links/"
	weight = 10
